# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c6c7444b-559c-4667-a5dc-f69f3f706dd5";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9474-4B25";
      fsType = "vfat";
    };

 fileSystems."/mnt/b" =
    { device = "/dev/dev/sda2";
      fsType = "ntfs-3g"; 
      options = [ "rw" "uid=1000"];
    };

 fileSystems."/mnt/c" =
    { device = "/dev/sdc3";
      fsType = "ntfs-3g"; 
      options = [ "rw" "uid=1000"];
    };

 fileSystems."/mnt/d" =
    { device = "/dev/nvme0n1p2";
      fsType = "ntfs-3g"; 
      options = [ "rw" "uid=1000"];
    };

 fileSystems."/mnt/g" =
    { device = "/dev/sdd1";
      fsType = "ntfs-3g"; 
      options = [ "rw" "uid=1000"];
    };

 fileSystems."/mnt/e" =
    { device = "/dev/sdd2";
      fsType = "ntfs-3g"; 
      options = [ "rw" "uid=1000"];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/17fd6741-48bb-4b8b-b652-e58e6f1d24a2"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
